### ISSUE TITLE
Problem with unused library functions

### ISSUE THREAD

**Issue by hcvazquez** [mbrevda/backbone-tableview#5]
My name is Hernan; with a group of colleagues we are conducting a research about unused code present in dependencies of JavaScript projects. We call this functions, UFF (Unused foreign functions). We found that in most projects there exist a great amount of UFF that are being included in the final bundle. 
 
In the case of backbone-tableview (v 1.0.5) our tools detected approximately 600 unused function in the dependencies (underscore, jquery, backbone-kinview, backbone, backbone-collectionview). Removing those functions, the size of backbone-tableview bundled could be reduced at least 50% (All tests passed). 

I’m attaching the reduced version of your project. 
[kinView(optimized).txt](https://github.com/mbrevda/backbone-tableview/files/671060/kinView.optimized.txt)

 
I’ll be very grateful if you can answer me the following questions:
-Did you were aware of the existence of these unused functions in your projects?
-Do you think that this is a problem? 

Thanks in advance.

Cheers,

**Comment by mbrevda** [comment]
Yes, no.

The deps are only included once in the final bundle. Hence, the only way to ascertain sulfurous functions would be to look at a real project and see which functions aren't being used in the final bundle. Furthermore, due to the lack of tree shaking tools at the time this lib as built, coupled with it's deps being almost exclusively es5, there really isn't much anyone can do about the unused functions.
